### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by MiloCasagrande** [marko-js/marko-loader#27]
After upgrading from 1.3.3 to 1.5.0, using `marko-loader` with `webpack`, I get the following error:

`Critical dependency: the request of a dependency is an expression`

I can reproduce the same issue using the `marko-webpack` repository after upgrading all dependencies in there.

This is the output taken from the `marko-webpack` repository when running `npm start`:
```
WARNING in ./src/components/app-tabs/index.marko 1:0-18
Critical dependency: the request of a dependency is an expression
 @ ./src/components/app/index.marko
 @ ./src/pages/home/client.js
```

When loading the app from a brwoser, the app itself is "broken": no CSS and no interactivity. This is the error I get from the browser console:
```
Uncaught Error: Cannot find module 'undefined'
```

Dependencies:
* marko 4.15.2
* marko-loader 1.5.0
* webpack 4.25.9
* webpack-cli 3.2.3

**Comment by sqrter** [comment]
+1

**Comment by jesse1983** [comment]
+1

**Comment by eltimn** [comment]
We're seeing this problem as well. We narrowed it down to the 1.4.0 release.

**Comment by arthurchenn** [comment]
Same problem here, last working version is 1.3.3.
Will it ever be fixed?

Dependencies:

    marko 4.18.25
    marko-loader 1.5.0
    webpack 4.41.2
